---
version: "3.9"
services:
  udpbroadcastrelay:
    image: brennanfee/docker-udpbroadcastrelay:latest
    container_name: udpbroadcastrelay
    restart: unless-stopped
    network_mode: host
    hostname: udpbroadcastrelay
    environment:
      - TZ=America/Chicago
    volumes:
      - /data/docker:/data
